### ISSUE TITLE
No authentication system

### ISSUE THREAD

**Issue by gilrosenthal** [ryanw-se/OvercastAPI#6]
For friends to list,add,remove and any upcoming features there needs to be auth. Maybe we could implement this via SunshineAPI? We have an auth api ready for you to use if you would like

**Comment by ryanw-se** [comment]
@gilrosenthal  There will be no direct coordination between projects. In time this API will implement its own authentication system in the implementation of the API which will remove the need to depend on a 3rd party service (Sunshine) in order to function properly.

Reliability is a big point in this project and great reliability can be achieved by avoiding as many 3rd party dependencies as possible. There would also be a major drop in performance & speed as well.
